import matplotlib
matplotlib.rcParams.update({
    'font.size': 14,
    'font.family': 'sans-serif',
    'font.sans-serif': ['Arial', 'Helvetica', 'DejaVu Sans'],
})
import matplotlib.pyplot as plt
import numpy as np
from scipy.interpolate import make_interp_spline


# Defined data points based on the study and conceptual orbital mechanics
# x represents Orbital Inclination from 0 to 90 degrees
x = np.array([0, 25, 45, 90])

# y_base represents Baseline (Polar-Only) network daily contact minutes
y_base = np.array([0, 0, 20, 100])

# y_aug represents Augmented (Polar + Equatorial Colombia) daily contact minutes
y_aug = np.array([125, 97.5, 60, 120])

# Generate smooth curves using spline interpolation
x_smooth = np.linspace(x.min(), x.max(), 300)

# k=2 is used for a smoother transition given the limited number of anchor points
spl_base = make_interp_spline(x, y_base, k=2)
spl_aug = make_interp_spline(x, y_aug, k=2)

y_base_smooth = spl_base(x_smooth)
y_aug_smooth = spl_aug(x_smooth)

# Ensure no negative values are generated by the spline curve
y_base_smooth = np.maximum(y_base_smooth, 0)
y_aug_smooth = np.maximum(y_aug_smooth, 0)

# Initialize the plot
plt.figure(figsize=(8, 5))

# Plot the smoothed lines
plt.plot(x_smooth, y_base_smooth, label='Baseline (Polar-Only)', color='blue', linestyle='--', linewidth=2)
plt.plot(x_smooth, y_aug_smooth, label='Augmented (Polar + Colombia)', color='green', linewidth=2)

# Plot the scatter points to show the exact anchor data
plt.scatter(x, y_base, color='blue', zorder=5)
plt.scatter(x, y_aug, color='green', zorder=5)

# Format the chart (Axes, limits, legend, and grid)
plt.xlabel('Orbital Inclination (°)')
plt.ylabel('Daily Contact Time (Minutes)')
plt.xlim(0, 90)
plt.ylim(0, 140)
plt.legend()
plt.grid(True, linestyle=':', alpha=0.7)

# Adjust layout and display the plot
plt.tight_layout()
plt.savefig('figure-02.png', dpi=300, bbox_inches='tight')
plt.show()

